#!/bin/python3
# Author : Jeremy Holodiline

from ipmininet.iptopo import IPTopo
from ipmininet.ipnet import IPNet
from ipmininet.cli import IPCLI

import sys
sys.path.insert(1, '/course/common/student/')
from ipmininet_exercices import IPMininet_Exercice
ex = IPMininet_Exercice(6)

class MyTopology(IPTopo):

    def build(self, *args, **kwargs):

        r1 = self.addRouter("r1")
        r2 = self.addRouter("r2")
        r3 = self.addRouter("r3")
        r4 = self.addRouter("r4")
        r5 = self.addRouter("r5")

        mask = 64
        subnet = ex.generate_subnet_addr(mask)
        lr1r2 = self.addLink(r1, r2, intfName1=ex.generate_intf_name("r1-r2"), intfName2=ex.generate_intf_name("r2-r1"))
        lr1r2[r1].addParams(ip=ex.generate_intf_addr("r1-r2", subnet, mask) + f"/{mask}")
        lr1r2[r2].addParams(ip=ex.generate_intf_addr("r2-r1", subnet, mask) + f"/{mask}")

        mask = 64
        subnet = ex.generate_subnet_addr(mask)
        lr2r3 = self.addLink(r2, r3, intfName1=ex.generate_intf_name("r2-r3"), intfName2=ex.generate_intf_name("r3-r2"))
        lr2r3[r2].addParams(ip=ex.generate_intf_addr("r2-r3", subnet, mask) + f"/{mask}")
        lr2r3[r3].addParams(ip=ex.generate_intf_addr("r3-r2", subnet, mask) + f"/{mask}")

        mask = 64
        subnet = ex.generate_subnet_addr(mask)
        lr3r4 = self.addLink(r3, r4, intfName1=ex.generate_intf_name("r3-r4"), intfName2=ex.generate_intf_name("r4-r3"))
        lr3r4[r3].addParams(ip=ex.generate_intf_addr("r3-r4", subnet, mask) + f"/{mask}")
        lr3r4[r4].addParams(ip=ex.generate_intf_addr("r4-r3", subnet, mask) + f"/{mask}")

        mask = 64
        subnet = ex.generate_subnet_addr(mask)
        lr1r4 = self.addLink(r1, r4, intfName1=ex.generate_intf_name("r1-r4"), intfName2=ex.generate_intf_name("r4-r1"))
        lr1r4[r1].addParams(ip=ex.generate_intf_addr("r1-r4", subnet, mask) + f"/{mask}")
        lr1r4[r4].addParams(ip=ex.generate_intf_addr("r4-r1", subnet, mask) + f"/{mask}")

        mask = 64
        subnet = ex.generate_subnet_addr(mask)
        lr2r5 = self.addLink(r2, r5, intfName1=ex.generate_intf_name("r2-r5"), intfName2=ex.generate_intf_name("r5-r2"))
        lr2r5[r2].addParams(ip=ex.generate_intf_addr("r2-r5", subnet, mask) + f"/{mask}")
        lr2r5[r5].addParams(ip=ex.generate_intf_addr("r5-r2", subnet, mask) + f"/{mask}")

        mask = 64
        subnet = ex.generate_subnet_addr(mask)
        lr3r5 = self.addLink(r3, r5, intfName1=ex.generate_intf_name("r3-r5"), intfName2=ex.generate_intf_name("r5-r3"))
        lr3r5[r3].addParams(ip=ex.generate_intf_addr("r3-r5", subnet, mask) + f"/{mask}")
        lr3r5[r5].addParams(ip=ex.generate_intf_addr("r5-r3", subnet, mask) + f"/{mask}")

        super(MyTopology, self).build(*args, **kwargs)

net = IPNet(topo=MyTopology(), allocate_IPs=False)

try:
    net.start()

    IPCLI(net)

    ex.traceroute_test("r1", "r5-r3", ["r2", "r3", "r5"], net)
    ex.traceroute_test("r5", "r1-r4", ["r2", "r3", "r4", "r1"], net)
    ex.send_feedback()

except Exception as e:
    ex.send_feedback(0, "crash", f"Error from the ipmininet script : {e}")

finally:
    net.stop()