#!/bin/python3
# Author : Jeremy Holodiline

from ipmininet.iptopo import IPTopo
from ipmininet.ipnet import IPNet
from ipmininet.cli import IPCLI
from ipmininet.router.config import RouterConfig

import sys
sys.path.insert(1, '/course/common/student/')
from ipmininet_exercices import IPMininet_Exercice
ex = IPMininet_Exercice(6)

class MyTopology(IPTopo):

    def build(self, *args, **kwargs):

        h1 = self.addHost("h1")
        h2 = self.addHost("h2")
        h3 = self.addHost("h3")
        h4 = self.addHost("h4")
        h5 = self.addHost("h5")
        r1 = self.addRouter("r1", config=RouterConfig)
        r2 = self.addRouter("r2", config=RouterConfig)
        r3 = self.addRouter("r3", config=RouterConfig)
        r4 = self.addRouter("r4", config=RouterConfig)
        r5 = self.addRouter("r5", config=RouterConfig)

        ex.create_link(self, h1, r1, 64)
        ex.create_link(self, h2, r2, 64)
        ex.create_link(self, h3, r3, 64)
        ex.create_link(self, h4, r4, 64)
        ex.create_link(self, h5, r5, 64)
        ex.create_link(self, r1, r2, 64)
        ex.create_link(self, r1, r3, 64)
        ex.create_link(self, r2, r3, 64)
        ex.create_link(self, r2, r5, 64)
        ex.create_link(self, r3, r4, 64)

        super(MyTopology, self).build(*args, **kwargs)

net = IPNet(topo=MyTopology(), allocate_IPs=False)

try:
    net.start()
    net["h1"].cmd("ip -6 route add default via " + ex.intf_addr["r1-h1"])
    net["h2"].cmd("ip -6 route add default via " + ex.intf_addr["r2-h2"])
    net["h3"].cmd("ip -6 route add default via " + ex.intf_addr["r3-h3"])
    net["h4"].cmd("ip -6 route add default via " + ex.intf_addr["r4-h4"])
    net["h5"].cmd("ip -6 route add default via " + ex.intf_addr["r5-h5"])
    net["r4"].cmd("ip -6 route add default via " + ex.intf_addr["r3-r4"])
    net["r5"].cmd("ip -6 route add default via " + ex.intf_addr["r2-r5"])
    net["r1"].cmd("ip -6 route add " + ex.intf_addr["h2-r2"] + "/64 via " + ex.intf_addr["r2-r1"])
    net["r1"].cmd("ip -6 route add " + ex.intf_addr["h3-r3"] + "/64 via " + ex.intf_addr["r3-r1"])
    net["r1"].cmd("ip -6 route add " + ex.intf_addr["h4-r4"] + "/64 via " + ex.intf_addr["r3-r1"])
    net["r1"].cmd("ip -6 route add " + ex.intf_addr["h5-r5"] + "/64 via " + ex.intf_addr["r2-r1"])
    net["r2"].cmd("ip -6 route add " + ex.intf_addr["h1-r1"] + "/64 via " + ex.intf_addr["r1-r2"])
    net["r2"].cmd("ip -6 route add " + ex.intf_addr["h3-r3"] + "/64 via " + ex.intf_addr["r3-r2"])
    net["r2"].cmd("ip -6 route add " + ex.intf_addr["h4-r4"] + "/64 via " + ex.intf_addr["r3-r2"])
    net["r2"].cmd("ip -6 route add " + ex.intf_addr["h5-r5"] + "/64 via " + ex.intf_addr["r5-r2"])
    net["r3"].cmd("ip -6 route add " + ex.intf_addr["h1-r1"] + "/64 via " + ex.intf_addr["r1-r3"])
    net["r3"].cmd("ip -6 route add " + ex.intf_addr["h2-r2"] + "/64 via " + ex.intf_addr["r2-r3"])
    net["r3"].cmd("ip -6 route add " + ex.intf_addr["h4-r4"] + "/64 via " + ex.intf_addr["r4-r3"])
    net["r3"].cmd("ip -6 route add " + ex.intf_addr["h5-r5"] + "/64 via " + ex.intf_addr["r2-r3"])

    IPCLI(net)

    for src in net.hosts:
        for dst in net.hosts:
            src_name = src.name
            dst_name = dst.name
            if src_name != dst_name:
                if src_name == "h4" or dst_name == "h4":
                    ex.output_test(src_name, f"nmap -6 --max-retries 0 " + ex.intf_addr[f"{dst_name}-r{dst_name[1]}"], "(0 hosts up)", "success", f"{src_name} was able to send packets to {dst_name}", net)
                else:
                    ex.output_test(src_name, f"nmap -6 --max-retries 0 " + ex.intf_addr[f"{dst_name}-r{dst_name[1]}"], "(1 host up)", "success", f"{src_name} could not send packets to {dst_name}", net)

    ex.send_feedback()

except Exception as e:
    ex.send_feedback(0, "crash", f"Error from the ipmininet script : {e}")

finally:
    net.stop()