#!/bin/python3
# Author : Jeremy Holodiline

from ipmininet.iptopo import IPTopo
from ipmininet.ipnet import IPNet
from ipmininet.cli import IPCLI
from ipmininet.router.config import RouterConfig

import random

import sys
sys.path.insert(1, '/course/common/student/')
from ipmininet_exercices import IPMininet_Exercice
ex = IPMininet_Exercice(6)

class MyTopology(IPTopo):

    def build(self, *args, **kwargs):

        h1 = self.addHost("h1")
        h2 = self.addHost("h2")
        h3 = self.addHost("h3")
        h4 = self.addHost("h4")
        r1 = self.addRouter("r1", config=RouterConfig)

        ex.create_link(self, h1, r1, 64)
        ex.create_link(self, h2, r1, 64)
        ex.create_link(self, h3, r1, 64)
        ex.create_link(self, h4, r1, 64)

        super(MyTopology, self).build(*args, **kwargs)

net = IPNet(topo=MyTopology(), allocate_IPs=False)

try:
    h1_port_to_drop = random.randint(65000, 65100)
    h2_port_to_drop = random.randint(65101, 65200)
    h3_port_to_remove = random.randint(65201, 65300)
    h3_port_to_not_remove = random.randint(65301, 65400)

    print(f"1) Add the rule to h1 that drops all incoming TCP packets for the {h1_port_to_drop} destination port")
    print(f"2) Add the rule to h2 that drops all outgoing TCP packets for the {h2_port_to_drop} destination port")
    print(f"3) Add the rule to r1 that drops all packets that should have been forwarded from h2 to h3")
    print(f"4) Remove the rule from h3 that drops all outgoing TCP packets for the {h3_port_to_remove} destination port (don't delete any other rule)")
    print(f"5) Add the rule to h4 that drops all incoming packets from h2")

    net.start()
    net["h3"].cmd(f"ip6tables -A OUTPUT -p tcp --dport {h3_port_to_remove} -j DROP")
    net["h3"].cmd(f"ip6tables -A OUTPUT -p tcp --dport {h3_port_to_not_remove} -j DROP")

    IPCLI(net)

    ex.output_test("h2", f"nmap -6 --max-retries 0 -p {h1_port_to_drop} {ex.intf_addr['h1-r1']}", "filtered", "success", f"1) h1 {h1_port_to_drop} port still reachable", net)
    ex.output_test("h2", f"nmap -6 --max-retries 0 -p {h2_port_to_drop} {ex.intf_addr['h1-r1']}", "filtered", "success", f"2) Outcome from h2 {h2_port_to_drop} port", net)
    ex.output_test("h2", f"ping -6 -c 1 -W 1 {ex.intf_addr['h3-r1']}", "100% packet loss", "success", f"3) h2 can still reach h3", net)
    ex.output_test("h3", f"nmap -6 --max-retries 0 -p {h3_port_to_remove} {ex.intf_addr['h1-r1']}", "closed", "success", f"4) Rule about h3 {h3_port_to_remove} port still there", net)
    ex.output_test("h3", f"nmap -6 --max-retries 0 -p {h3_port_to_not_remove} {ex.intf_addr['h1-r1']}", "filtered", "success", f"4) An other r3 rule has been deleted when it should not have", net)
    ex.output_test("h2", f"ping -6 -c 1 -W 1 {ex.intf_addr['h4-r1']}", "100% packet loss", "success", f"5) h2 can still reach h4", net)
    ex.send_feedback()

except Exception as e:
    ex.send_feedback(0, "crash", f"Error from the ipmininet script : {e}")

finally:
    net.stop()