#!/bin/python3
# Author : Jeremy Holodiline

from ipmininet.iptopo import IPTopo
from ipmininet.ipnet import IPNet
from ipmininet.cli import IPCLI

import sys
sys.path.insert(1, '/course/common/student/')
from ipmininet_exercices import IPMininet_Exercice
ex = IPMininet_Exercice(6)

class MyTopology(IPTopo):

    def build(self, *args, **kwargs):

        r1 = self.addRouter("r1")
        r2 = self.addRouter("r2")
        r3 = self.addRouter("r3")
        r4 = self.addRouter("r4")

        ex.create_link(self, r1, r2, 64)
        ex.create_link(self, r2, r3, 64)
        ex.create_link(self, r3, r4, 64)

        routers = ["r1","r2","r3","r4"]
        for r in routers:
            mask = 64
            ex.generate_intf_addr(f"{r}-lo", ex.generate_subnet_addr(mask), mask)

        super(MyTopology, self).build(*args, **kwargs)

net = IPNet(topo=MyTopology(), allocate_IPs=False)

try:
    routers = ["r1","r2","r3","r4"]
    for r in routers:
        print(f"{r} must be configured with the loopback address : {ex.intf_addr[f'{r}-lo']}/128")

    net.start()
    for r in routers:
        net[r].cmd("vtysh -c 'configure terminal' -c 'router ospf6' -c 'no interface lo area 0.0.0.0' -c 'exit' -c 'exit' -c 'write memory'")

    IPCLI(net)

    for r in routers:
        ex.output_test(f"{r}", "vtysh -c 'show ipv6 ospf6 interface lo'", f"inet6: {ex.intf_addr[f'{r}-lo']}/128", f"{r} has the correct loopback address", f"{r} has not the correct loopback address", net)

    for r_a in routers:
        for r_b in routers:
            if r_a != r_b:
                ex.ping_test(f"{r_a}", f"{r_b}-lo", net)

    ex.send_feedback()

except Exception as e:
    ex.send_feedback(0, "crash", f"Error from the ipmininet script : {e}")

finally:
    net.stop()