#!/bin/python3
# Authors : Emilie Deprez, Jeremy Holodiline

from ipmininet.iptopo import IPTopo
from ipmininet.ipnet import IPNet
from ipmininet.cli import IPCLI
from ipmininet.router.config import RouterConfig

import random

import sys
sys.path.insert(1, '/course/common/student/')
from ipmininet_exercices import IPMininet_Exercice
ex = IPMininet_Exercice(6)

class MyTopology(IPTopo):

    def build(self, *args, **kwargs):

        h1 = self.addHost("h1", defaultRoute=None)
        h2 = self.addHost("h2", defaultRoute=None)
        r1 = self.addRouter("r1", config=RouterConfig)
        r2 = self.addRouter("r2", config=RouterConfig)

        ex.create_link(self, h1, r1, 64)
        ex.create_link(self, r1, r2, 64)
        ex.create_link(self, h2, r2, 64)

        super(MyTopology, self).build(*args, **kwargs)

net = IPNet(topo=MyTopology(), allocate_IPs=False)

try:
    bad_route = "2001:bad:1341:" + str(format(random.randint(1, 0xffff), "x")) + "::"

    net.start()
    net["r1"].cmd("ip -6 route add " + bad_route + "/64 via " + ex.intf_addr["r2-r1"])
    net["r2"].cmd("ip -6 route add default via " + ex.intf_addr["h2-r2"])

    IPCLI(net)

    ex.ping_test("h1", "h2-r2", net)
    ex.ping_test("h2", "h1-r1", net)
    ex.route_test("r1", bad_route + "/64", ex.intf_addr["r2-r1"], False, net)
    ex.send_feedback()

except Exception as e:
    ex.send_feedback(0, "crash", f"Error from the ipmininet script : {e}")

finally:
    net.stop()