#!/bin/python3
# Authors : Emilie Deprez, Jeremy Holodiline

from ipmininet.iptopo import IPTopo
from ipmininet.ipnet import IPNet
from ipmininet.cli import IPCLI
from ipmininet.router.config import RouterConfig

import sys
sys.path.insert(1, '/course/common/student/')
from ipmininet_exercices import IPMininet_Exercice
ex = IPMininet_Exercice(6)

class MyTopology(IPTopo):

    def build(self, *args, **kwargs):

        h1 = self.addHost("h1", defaultRoute=None)
        h2 = self.addHost("h2", defaultRoute=None)
        h3 = self.addHost("h3", defaultRoute=None)
        r1 = self.addRouter("r1", config=RouterConfig)
        r2 = self.addRouter("r2", config=RouterConfig)
        r3 = self.addRouter("r3", config=RouterConfig)
        r4 = self.addRouter("r4", config=RouterConfig)

        ex.create_link(self, h1, r1, 64)
        ex.create_link(self, r1, r2, 64)
        ex.create_link(self, r2, r3, 64)
        ex.create_link(self, r1, r3, 64)
        ex.create_link(self, r3, r4, 64)
        ex.create_link(self, r4, h3, 64)
        ex.create_link(self, r3, h2, 64)

        super(MyTopology, self).build(*args, **kwargs)

net = IPNet(topo=MyTopology(), allocate_IPs=False)

try:
    net.start()

    net["h1"].cmd("ip -6 route add default via " + ex.intf_addr["r1-h1"])
    net["h2"].cmd("ip -6 route add default via " + ex.intf_addr["r3-h2"])
    net["h3"].cmd("ip -6 route add default via " + ex.intf_addr["r4-h3"])
    net["r1"].cmd("ip -6 route add " + ex.intf_addr["h3-r4"] + "/64 via " + ex.intf_addr["r2-r1"])
    net["r1"].cmd("ip -6 route add " + ex.intf_addr["h2-r3"] + "/64 via " + ex.intf_addr["r3-r1"])
    net["r2"].cmd("ip -6 route add " + ex.intf_addr["h3-r4"] + "/64 via " + ex.intf_addr["r3-r2"])
    net["r4"].cmd("ip -6 route add default via " + ex.intf_addr["r3-r4"])
    net["r3"].cmd("ip -6 route add " + ex.intf_addr["h3-r4"] + "/64 via " + ex.intf_addr["r4-r3"])

    IPCLI(net)

    ex.ping_test("h1", "h2-r3", net)
    ex.ping_test("h1", "h3-r4", net)
    ex.ping_test("h2", "h1-r1", net)
    ex.ping_test("h2", "h3-r4", net)
    ex.ping_test("h3", "h1-r1", net)
    ex.ping_test("h3", "h2-r3", net)
    ex.send_feedback()

except Exception as e:
    ex.send_feedback(0, "crash", f"Error from the ipmininet script : {e}")

finally:
    net.stop()