#!/bin/python3
# Author : Jeremy Holodiline

from ipmininet.iptopo import IPTopo
from ipmininet.ipnet import IPNet
from ipmininet.cli import IPCLI

import random

import sys
sys.path.insert(1, '/course/common/student/')
from ipmininet_exercices import IPMininet_Exercice
ex = IPMininet_Exercice(6)

class MyTopology(IPTopo):

    def build(self, *args, **kwargs):

        s_var_names = ["a", "b", "c", "d", "e"]
        s_var = {}
        s_num = list(range(1,100))
        for var_name in s_var_names:
            rand_s_num = random.choice(s_num)
            s_var[var_name] = self.addSwitch(f"s{rand_s_num}", prio=rand_s_num)
            s_num.remove(rand_s_num)

        ex.create_link_switch(self, s_var["a"], s_var["b"])
        ex.create_link_switch(self, s_var["a"], s_var["d"])
        ex.create_link_switch(self, s_var["a"], s_var["e"])
        ex.create_link_switch(self, s_var["b"], s_var["c"])
        ex.create_link_switch(self, s_var["c"], s_var["d"])
        ex.create_link_switch(self, s_var["d"], s_var["e"])

        super(MyTopology, self).build(*args, **kwargs)

def answer(cli, args):
    ex.student_answer = ",".join(sorted(args.split(",")))

net = IPNet(topo=MyTopology())

try:
    net.start()

    IPCLI.do_answer = answer

    IPCLI(net)

    correct = ""
    for s in net.switches:
        lines = net[s.name].cmd(f"bridge link show").splitlines()
        for i in range(len(lines)):
            if "blocking" in lines[i]:
                correct += lines[i].split(" ")[1].split("@")[0] + ","
        break
    ex.correct_answer = "none" if correct == "" else ",".join(sorted(correct.rstrip(",").split(",")))
    ex.compare_answer_test()
    ex.send_feedback()

except Exception as e:
    ex.send_feedback(0, "crash", f"Error from the ipmininet script : {e}")

finally:
    net.stop()