#!/bin/python3
# Author : Jeremy Holodiline

from ipmininet.iptopo import IPTopo
from ipmininet.ipnet import IPNet
from ipmininet.cli import IPCLI

import random

def store_feedback(grade, result, feedback):
    STORE = True
    if STORE:
        with open("tmp/student/feedback.txt", "w") as f:
            f.write(str(grade) + "\n")
            f.write(result + "\n")
            f.write(feedback)
    else:
        print(f"Grade : {grade}")
        print(f"Result : {result}")
        print(f"Feedback : {feedback}")

interface_addr = dict()

def generate_IP_addr(interface, version, prefix):
    while True:
        addr = ""
        if version == "v4":
            if prefix != "" and prefix[-1] != ".": prefix += "."
            n_rand = 4 - (len(prefix.split(".")) - 1)
            addr = prefix + ".".join(("%s" % random.randint(0, 255) for _ in range(n_rand)))
            addr = addr.rstrip(".")
        elif version == "v6":
            if prefix != "" and prefix[-1] != ":": prefix += ":"
            n_rand = 8 - (len(prefix.split(":")) - 1)
            addr = prefix + ":".join(("%s" % format(random.randint(0, 0xffff), "x") for _ in range(n_rand)))
            addr = addr.rstrip(":")
        else: raise ValueError("IP version must be \"v4\" or \"v6\"")
        if addr not in interface_addr.values():
            interface_addr[interface] = addr
            return addr

class MyTopology(IPTopo):

    def build(self, *args, **kwargs):

        r1 = self.addRouter("r1")
        r2 = self.addRouter("r2")
        r3 = self.addRouter("r3")
        r4 = self.addRouter("r4")

        prefix = ":".join(("%s" % format(random.randint(0, 0xffff), "x") for _ in range(3)))

        lr1r2 = self.addLink(r1, r2)
        lr1r2[r1].addParams(ip = generate_IP_addr("r1-r2", "v6", f"{prefix}:1:") + "/64")
        lr1r2[r2].addParams(ip = generate_IP_addr("r2-r1", "v6", f"{prefix}:1:") + "/64")

        lr2r3 = self.addLink(r2, r3)
        lr2r3[r2].addParams(ip = generate_IP_addr("r2-r3", "v6", f"{prefix}:2:") + "/64")
        lr2r3[r3].addParams(ip = generate_IP_addr("r3-r2", "v6", f"{prefix}:2:") + "/64")

        lr3r4 = self.addLink(r3, r4)
        lr3r4[r3].addParams(ip = generate_IP_addr("r3-r4", "v6", f"{prefix}:3:") + "/64")
        lr3r4[r4].addParams(ip = generate_IP_addr("r4-r3", "v6", f"{prefix}:3:") + "/64")

        generate_IP_addr("r1-lo", "v6", "")
        generate_IP_addr("r2-lo", "v6", "")
        generate_IP_addr("r3-lo", "v6", "")
        generate_IP_addr("r4-lo", "v6", "")

        super(MyTopology, self).build(*args, **kwargs)

class Test:

    def __init__(self):
        self.n_test = 0
        self.n_success_test = 0
        self.feedback = ""
    
    def ping_test(self, src_name, dst_interface_name, net):
        self.n_test += 1
        dst_address = interface_addr[dst_interface_name]
        dst_name = dst_interface_name.split("-")[0]
        dst_IP_version = "6" if ":" in dst_address else "4"
        output = ""
        try:
            output = net[src_name].cmd(f"ping -{dst_IP_version} -c 1 -W 1 {dst_address}")
        except Exception as e:
            self.feedback += f"Ping {src_name} -> {dst_name} error : {e}\n"
            return
        if " 0% packet loss" in output or " 0.0% packet loss" in output:
            self.n_success_test += 1
            self.feedback += f"Ping {src_name} -> {dst_name} success\n"
        else:
            self.feedback += f"Ping {src_name} -> {dst_name} failed : {output}\n"

    def config_test(self, node, command, expected, success_msg, failed_msg):
        self.n_test += 1
        output = ""
        try:
            output = net[node].cmd(command)
        except Exception as e:
            self.feedback += f"{node} {command} error : {e}\n"
            return
        if expected in output:
            self.n_success_test += 1
            self.feedback += f"Success : {success_msg}\n"
        else:
            self.feedback += f"Failed : {failed_msg}\n"

    def send_feedback(self):
        grade = 100 if self.n_test == 0 else ((self.n_success_test / self.n_test) * 100)
        result = "success" if grade == 100 else "failed"
        store_feedback(grade, result, self.feedback)

def get_instructions(cli, args):
    print(f"r1 must be configured with the loopback address : {interface_addr['r1-lo']}/128")
    print(f"r2 must be configured with the loopback address : {interface_addr['r2-lo']}/128")
    print(f"r3 must be configured with the loopback address : {interface_addr['r3-lo']}/128")
    print(f"r4 must be configured with the loopback address : {interface_addr['r4-lo']}/128")

net = IPNet(topo=MyTopology(), allocate_IPs=False)

try:
    net.start()

    IPCLI.do_getinstructions = get_instructions

    IPCLI(net)

    test = Test()
    test.config_test("r1", "vtysh -c 'show ipv6 ospf6 interface lo'", f"inet6: {interface_addr['r1-lo']}/128", "r1 has the correct loopback address", "r1 has not the correct loopback address")
    test.config_test("r2", "vtysh -c 'show ipv6 ospf6 interface lo'", f"inet6: {interface_addr['r2-lo']}/128", "r2 has the correct loopback address", "r2 has not the correct loopback address")
    test.config_test("r3", "vtysh -c 'show ipv6 ospf6 interface lo'", f"inet6: {interface_addr['r3-lo']}/128", "r3 has the correct loopback address", "r3 has not the correct loopback address")
    test.config_test("r4", "vtysh -c 'show ipv6 ospf6 interface lo'", f"inet6: {interface_addr['r4-lo']}/128", "r4 has the correct loopback address", "r4 has not the correct loopback address")
    test.ping_test("r1", "r2-lo", net)
    test.ping_test("r1", "r3-lo", net)
    test.ping_test("r1", "r4-lo", net)
    test.ping_test("r2", "r1-lo", net)
    test.ping_test("r2", "r3-lo", net)
    test.ping_test("r2", "r4-lo", net)
    test.ping_test("r3", "r1-lo", net)
    test.ping_test("r3", "r2-lo", net)
    test.ping_test("r3", "r4-lo", net)
    test.ping_test("r4", "r1-lo", net)
    test.ping_test("r4", "r2-lo", net)
    test.ping_test("r4", "r3-lo", net)
    test.send_feedback()

except Exception as e:
    store_feedback(0, "crash", f"Error from the ipmininet script : {e}")

finally:
    net.stop()