ex.exec_cmd(asAr1.name, f"vtysh -c 'configure terminal' -c 'router bgp {ex.get_asn('A')}' -c 'network {asAr1_asBr1_addr}/{ex.subnet_addr[asAr1_asBr1_subnet]}' -c 'neighbor {asBr1_asAr1_addr} remote-as {ex.get_asn('B')}' -c 'exit' -c 'exit' -c 'write memory'")
ex.exec_cmd(asBr1.name, f"vtysh -c 'configure terminal' -c 'router bgp {ex.get_asn('B')}' -c 'network {asBr1_asAr1_addr}/{ex.subnet_addr[asAr1_asBr1_subnet]}' -c 'neighbor {asAr1_asBr1_addr} remote-as {ex.get_asn('A')}' -c 'exit' -c 'exit' -c 'write memory'")
ex.run_client()

ex.exec_cmd(asAr1.name, f"vtysh -c 'configure terminal' -c 'router bgp {ex.get_asn('A')}' -c 'neighbor {asAr2_lo_addr} remote-as {ex.get_asn('A')}' -c 'neighbor {asAr2_lo_addr} update-source lo' -c 'neighbor {asAr2_lo_addr} next-hop-self' -c 'neighbor {asAr3_lo_addr} remote-as {ex.get_asn('A')}' -c 'neighbor {asAr3_lo_addr} update-source lo' -c 'neighbor {asAr3_lo_addr} next-hop-self' -c 'exit' -c 'exit' -c 'write memory'")
ex.exec_cmd(asAr2.name, f"vtysh -c 'configure terminal' -c 'router bgp {ex.get_asn('A')}' -c 'neighbor {asAr1_lo_addr} remote-as {ex.get_asn('A')}' -c 'neighbor {asAr1_lo_addr} update-source lo' -c 'neighbor {asAr1_lo_addr} next-hop-self' -c 'neighbor {asAr3_lo_addr} remote-as {ex.get_asn('A')}' -c 'neighbor {asAr3_lo_addr} update-source lo' -c 'neighbor {asAr3_lo_addr} next-hop-self' -c 'exit' -c 'exit' -c 'write memory'")
ex.exec_cmd(asAr3.name, f"vtysh -c 'configure terminal' -c 'router bgp {ex.get_asn('A')}' -c 'neighbor {asAr1_lo_addr} remote-as {ex.get_asn('A')}' -c 'neighbor {asAr1_lo_addr} update-source lo' -c 'neighbor {asAr1_lo_addr} next-hop-self' -c 'neighbor {asAr2_lo_addr} remote-as {ex.get_asn('A')}' -c 'neighbor {asAr2_lo_addr} update-source lo' -c 'neighbor {asAr2_lo_addr} next-hop-self' -c 'exit' -c 'exit' -c 'write memory'")
ex.run_client()

ex.exec_cmd(asAr1.name, f"vtysh -c 'configure terminal' -c 'router bgp {ex.get_asn('A')}' -c 'network {asAr1_asBr1_addr}/{ex.subnet_addr[asAr1_asBr1_subnet]}' -c 'neighbor {asBr1_asAr1_addr} remote-as {ex.get_asn('B')}' -c 'redistribute ospf' -c 'neighbor {asAr2_lo_addr} remote-as {ex.get_asn('A')}' -c 'neighbor {asAr2_lo_addr} update-source lo' -c 'neighbor {asAr2_lo_addr} next-hop-self' -c 'neighbor {asAr3_lo_addr} remote-as {ex.get_asn('A')}' -c 'neighbor {asAr3_lo_addr} update-source lo' -c 'neighbor {asAr3_lo_addr} next-hop-self' -c 'exit' -c 'exit' -c 'write memory'")
ex.exec_cmd(asAr2.name, f"vtysh -c 'configure terminal' -c 'router bgp {ex.get_asn('A')}' -c 'neighbor {asAr1_lo_addr} remote-as {ex.get_asn('A')}' -c 'neighbor {asAr1_lo_addr} update-source lo' -c 'neighbor {asAr1_lo_addr} next-hop-self' -c 'neighbor {asAr3_lo_addr} remote-as {ex.get_asn('A')}' -c 'neighbor {asAr3_lo_addr} update-source lo' -c 'neighbor {asAr3_lo_addr} next-hop-self' -c 'exit' -c 'exit' -c 'write memory'")
ex.exec_cmd(asAr3.name, f"vtysh -c 'configure terminal' -c 'router bgp {ex.get_asn('A')}' -c 'neighbor {asAr1_lo_addr} remote-as {ex.get_asn('A')}' -c 'neighbor {asAr1_lo_addr} update-source lo' -c 'neighbor {asAr1_lo_addr} next-hop-self' -c 'neighbor {asAr2_lo_addr} remote-as {ex.get_asn('A')}' -c 'neighbor {asAr2_lo_addr} update-source lo' -c 'neighbor {asAr2_lo_addr} next-hop-self' -c 'exit' -c 'exit' -c 'write memory'")
ex.exec_cmd(asBr1.name, f"vtysh -c 'configure terminal' -c 'router bgp {ex.get_asn('B')}' -c 'network {asBr1_asAr1_addr}/{ex.subnet_addr[asAr1_asBr1_subnet]}' -c 'neighbor {asAr1_asBr1_addr} remote-as {ex.get_asn('A')}' -c 'redistribute ospf' -c 'neighbor {asBr2_lo_addr} remote-as {ex.get_asn('B')}' -c 'neighbor {asBr2_lo_addr} update-source lo' -c 'neighbor {asBr2_lo_addr} next-hop-self' -c 'neighbor {asBr3_lo_addr} remote-as {ex.get_asn('B')}' -c 'neighbor {asBr3_lo_addr} update-source lo' -c 'neighbor {asBr3_lo_addr} next-hop-self' -c 'exit' -c 'exit' -c 'write memory'")
ex.exec_cmd(asBr2.name, f"vtysh -c 'configure terminal' -c 'router bgp {ex.get_asn('B')}' -c 'neighbor {asBr1_lo_addr} remote-as {ex.get_asn('B')}' -c 'neighbor {asBr1_lo_addr} update-source lo' -c 'neighbor {asBr1_lo_addr} next-hop-self' -c 'neighbor {asBr3_lo_addr} remote-as {ex.get_asn('B')}' -c 'neighbor {asBr3_lo_addr} update-source lo' -c 'neighbor {asBr3_lo_addr} next-hop-self' -c 'exit' -c 'exit' -c 'write memory'")
ex.exec_cmd(asBr3.name, f"vtysh -c 'configure terminal' -c 'router bgp {ex.get_asn('B')}' -c 'neighbor {asBr1_lo_addr} remote-as {ex.get_asn('B')}' -c 'neighbor {asBr1_lo_addr} update-source lo' -c 'neighbor {asBr1_lo_addr} next-hop-self' -c 'neighbor {asBr2_lo_addr} remote-as {ex.get_asn('B')}' -c 'neighbor {asBr2_lo_addr} update-source lo' -c 'neighbor {asBr2_lo_addr} next-hop-self' -c 'exit' -c 'exit' -c 'write memory'")
ex.run_client()

ex.exec_cmd(asAr1.name, f"vtysh -c 'configure terminal' -c 'route-map ACCEPT_ALL permit 10' -c 'exit' -c 'route-map MED permit 20' -c 'set metric 100' -c 'exit' -c 'router bgp {ex.get_asn('A')}' -c 'neighbor {asAr2_asAr1_addr} route-map ACCEPT_ALL in' -c 'neighbor {asAr2_asAr1_addr} route-map ACCEPT_ALL out' -c 'neighbor {asBr1_asAr1_addr} route-map ACCEPT_ALL in' -c 'neighbor {asBr1_asAr1_addr} route-map ACCEPT_ALL out' -c 'neighbor {asBr1_asAr1_addr} route-map MED out' -c 'exit' -c 'exit' -c 'write memory'")
ex.exec_cmd(asAr2.name, f"vtysh -c 'configure terminal' -c 'route-map ACCEPT_ALL permit 10' -c 'exit' -c 'router bgp {ex.get_asn('A')}' -c 'neighbor {asAr1_asAr2_addr} route-map ACCEPT_ALL in' -c 'neighbor {asAr1_asAr2_addr} route-map ACCEPT_ALL out' -c 'neighbor {asBr1_asAr2_addr} route-map ACCEPT_ALL in' -c 'neighbor {asBr1_asAr2_addr} route-map ACCEPT_ALL out' -c 'exit' -c 'exit' -c 'write memory'")
ex.exec_cmd(asBr1.name, f"vtysh -c 'configure terminal' -c 'route-map ACCEPT_ALL permit 10' -c 'exit' -c 'router bgp {ex.get_asn('B')}' -c 'neighbor {asAr1_asBr1_addr} route-map ACCEPT_ALL in' -c 'neighbor {asAr1_asBr1_addr} route-map ACCEPT_ALL out' -c 'neighbor {asAr2_asBr1_addr} route-map ACCEPT_ALL in' -c 'neighbor {asAr2_asBr1_addr} route-map ACCEPT_ALL out' -c 'exit' -c 'exit' -c 'write memory'")
ex.run_client()

ex.exec_cmd(asAr1.name, f"vtysh -c 'configure terminal' -c 'route-map LOCPRF permit 20' -c 'set local-preference 5' -c 'exit' -c 'router bgp {ex.get_asn('A')}' -c 'neighbor {asDr1_asAr1_addr} route-map LOCPRF in' -c 'exit' -c 'exit' -c 'write memory'")
ex.run_client()

deny_asC = f"DENY_AS{ex.get_asn('C')}_PREFIX"
ex.exec_cmd(asAr1.name, f"vtysh -c 'configure terminal' -c 'ip prefix-list {deny_asC} seq 1 deny {asAr1_asCr1_subnet}/{ex.subnet_addr[asAr1_asCr1_subnet]}' -c 'route-map {deny_asC} deny 10' -c 'match ip address prefix-list {deny_asC}' -c 'exit' -c 'router bgp {ex.get_asn('A')}' -c 'neighbor {asCr1_asAr1_addr} route-map {deny_asC} in' -c 'neighbor {asCr1_asAr1_addr} route-map {deny_asC} out' -c 'exit' -c 'exit' -c 'write memory'")
ex.exec_cmd(asBr1.name, f"vtysh -c 'configure terminal' -c 'ip prefix-list {deny_asC} seq 1 deny {asBr1_asCr1_subnet}/{ex.subnet_addr[asBr1_asCr1_subnet]}' -c 'route-map {deny_asC} deny 10' -c 'match ip address prefix-list {deny_asC}' -c 'exit' -c 'router bgp {ex.get_asn('B')}' -c 'neighbor {asCr1_asBr1_addr} route-map {deny_asC} in' -c 'neighbor {asCr1_asBr1_addr} route-map {deny_asC} out' -c 'exit' -c 'exit' -c 'write memory'")
ex.run_client()

ex.exec_cmd(asAr1.name, f"vtysh -c 'configure terminal' -c 'route-map SET_COMMUNITY permit 10' -c 'set community {ex.get_asn('A')}:100' -c 'exit' -c 'router bgp {ex.get_asn('A')}' -c 'no network {asAr1_asBr1_addr}/{ex.subnet_addr[asAr1_asBr1_subnet]}' -c 'network {asAr1_asBr1_addr}/{ex.subnet_addr[asAr1_asBr1_subnet]} route-map SET_COMMUNITY' -c 'exit' -c 'exit' -c 'write memory'")
ex.exec_cmd(asBr1.name, f"vtysh -c 'configure terminal' -c 'ip prefix-list TO_ADVERTISE seq 10 permit {asBr1_asCr1_subnet}/{ex.subnet_addr[asBr1_asCr1_subnet]}' -c 'route-map FILTER_COMMUNITY deny 5' -c 'match community {ex.get_asn('A')}:100' -c 'exit' -c 'route-map FILTER_COMMUNITY permit 10' -c 'match ip address prefix-list TO_ADVERTISE' -c 'exit' -c 'router bgp {ex.get_asn('B')}' -c 'neighbor {asDr1_asBr1_addr} route-map FILTER_COMMUNITY out' -c 'exit' -c 'exit' -c 'write memory'")
ex.run_client()

ex.exec_cmd(asAr1.name, f"vtysh -c 'configure terminal' -c 'router bgp {ex.get_asn('A')}' -c 'neighbor {asAr2_lo_addr} next-hop-self' -c 'exit' -c 'exit' -c 'write memory'")
ex.run_client()