#!/bin/python3
# Author : Jeremy Holodiline

from inginious import feedback, ssh_student
from ipmininet.iptopo import IPTopo
from ipmininet.ipnet import IPNet
from ipmininet.cli import IPCLI
from ipmininet.router.config import RouterConfig, STATIC
import random

addresses = dict()

def generateIPaddr(interface, version):
    while True:
        if version == "v4":
            addr = "192.168." + ".".join(("%s" % random.randint(0, 255) for _ in range(2)))
        elif version == "v6":
            addr = "2001:db8:1234:1341:" + ":".join(("%s" % "".join(("%s" % random.choice(("0","1","2","3","4","5","6","7","8","9","a","b","c","d","e","f")) for _ in range(4))) for _ in range(4)))
        else:
            raise ValueError("IP version must be \"v4\" or \"v6\"")
        if addr not in addresses.values():
            addresses[interface] = addr
            return addr

class MyTopology(IPTopo):

    def build(self, *args, **kwargs):

        h1 = self.addHost("h1", defaultRoute=None)
        h2 = self.addHost("h2", defaultRoute=None)
        h3 = self.addHost("h3", defaultRoute=None)
        r1 = self.addRouter("r1", config=RouterConfig)
        r2 = self.addRouter("r2", config=RouterConfig)
        r3 = self.addRouter("r3", config=RouterConfig)
        r4 = self.addRouter("r4", config=RouterConfig)

        lh1r1 = self.addLink(h1, r1)
        lh1r1[h1].addParams(ip=generateIPaddr("h1r1", "v6") + "/64")
        lh1r1[r1].addParams(ip=generateIPaddr("r1h1", "v6") + "/64")

        lr1r2 = self.addLink(r1, r2)
        lr1r2[r1].addParams(ip=generateIPaddr("r1r2", "v6") + "/64")
        lr1r2[r2].addParams(ip=generateIPaddr("r2r1", "v6") + "/64")

        lr1r3 = self.addLink(r1, r3)
        lr1r3[r1].addParams(ip=generateIPaddr("r1r3", "v6") + "/64")
        lr1r3[r3].addParams(ip=generateIPaddr("r3r1", "v6") + "/64")

        lr2r4 = self.addLink(r2, r4)
        lr2r4[r2].addParams(ip=generateIPaddr("r2r4", "v6") + "/64")
        lr2r4[r4].addParams(ip=generateIPaddr("r4r2", "v6") + "/64")

        lr3r4 = self.addLink(r3, r4)
        lr3r4[r3].addParams(ip=generateIPaddr("r3r4", "v6") + "/64")
        lr3r4[r4].addParams(ip=generateIPaddr("r4r3", "v6") + "/64")

        lh2r2 = self.addLink(r2, h2)
        lh2r2[h2].addParams(ip=generateIPaddr("h2r2", "v6") + "/64")
        lh2r2[r2].addParams(ip=generateIPaddr("r2h2", "v6") + "/64")

        lh3r3 = self.addLink(r3, h3)
        lh3r3[h3].addParams(ip=generateIPaddr("h3r3", "v6") + "/64")
        lh3r3[r3].addParams(ip=generateIPaddr("r3h3", "v6") + "/64")

        r1.addDaemon(STATIC, static_routes=[])
        r2.addDaemon(STATIC, static_routes=[])
        r3.addDaemon(STATIC, static_routes=[])
        r4.addDaemon(STATIC, static_routes=[])

        super(MyTopology, self).build(*args, **kwargs)

net = IPNet(topo=MyTopology(), allocate_IPs=False)

try:
    net.start()
    net["h1"].cmd("ip -6 route add default via " + addresses["r1h1"])
    net["h2"].cmd("ip -6 route add default via " + addresses["r2h2"])
    net["h3"].cmd("ip -6 route add default via " + addresses["r3h3"])
    net["r1"].cmd("ip -6 route add default via " + addresses["r2r1"])
    net["r2"].cmd("ip -6 route add default via " + addresses["r4r2"])
    net["r3"].cmd("ip -6 route add default via " + addresses["r1r3"])
    net["r4"].cmd("ip -6 route add default via " + addresses["r3r4"])
    net["r1"].cmd("ip -6 route add " + addresses["h3r3"] + "/64 via " + addresses["r3r1"])
    net["r2"].cmd("ip -6 route add " + addresses["h1r1"] + "/64 via " + addresses["r1r2"])

    IPCLI(net)
    ssh_student.ssh_student()

    feedback.set_grade(100)
    feedback.set_global_feedback("Success")
    feedback.set_global_result("success")
    
except Exception as e:
    feedback.set_grade(0)
    feedback.set_global_feedback(f"{e}")
    feedback.set_global_result("failed")

finally:
    net.stop()